//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razansmadi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chalet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chalet()
        {
            this.Bookings = new HashSet<Booking>();
            this.CategoriesChalets = new HashSet<CategoriesChalet>();
            this.Comments = new HashSet<Comment>();
            this.Faves = new HashSet<Fave>();
            this.transactions = new HashSet<transaction>();
            this.votes = new HashSet<vote>();
        }
    
        public int ChaletID { get; set; }
        public string userid { get; set; }
        public string Chalet_Name { get; set; }
        public string Chalet_Description { get; set; }
        public string Chalet_Address { get; set; }
        public Nullable<int> AvailabilityFlag { get; set; }
        public Nullable<int> NnmberOfAdult { get; set; }
        public Nullable<int> NnmberOfkid { get; set; }
        public Nullable<decimal> PricePerNight { get; set; }
        public Nullable<int> Images_ID { get; set; }
        public Nullable<int> Features_ID { get; set; }
        public Nullable<bool> isAccepted { get; set; }
        public Nullable<int> bedroom { get; set; }
        public Nullable<int> bathroom { get; set; }
        public Nullable<double> area { get; set; }
        public Nullable<bool> super { get; set; }
        public string map { get; set; }
        public Nullable<System.DateTime> DateOfReg { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesChalet> CategoriesChalets { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fave> Faves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> votes { get; set; }
    }
}
