//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razansmadi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.Chalets = new HashSet<Chalet>();
        }
    
        public int Images_ID { get; set; }
        public string MainImage { get; set; }
        public string poolImage { get; set; }
        public string gardenImage { get; set; }
        public string playGroundImage { get; set; }
        public string roomImage { get; set; }
        public string kitchenImage { get; set; }
        public string livingRoomImage { get; set; }
        public string bathroomImage { get; set; }
        public string viewImage { get; set; }
        public string randomImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chalet> Chalets { get; set; }
    }
}
